# -*- coding: utf-8 -*-
"""endometrial_balance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xMDn1GHocmBSPUhbEQrqOODyS1Vn6SZ
"""

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import shutil, random

def balance_dataset(data_path, strategy='oversample'):
    target_dir = Path('/content/balanced_data')
    target_dir.mkdir(parents=True, exist_ok=True)

    classes = [cls.name for cls in data_path.iterdir() if cls.is_dir()]

    counts = {}
    for cls_name in classes:
        class_dir = data_path / cls_name
        image_files = [f for f in class_dir.iterdir() if f.is_file() and f.suffix.lower() in ['.jpg', '.jpeg']]
        counts[cls_name] = len(image_files)

    print("Original class counts:", counts)

    max_count = max(counts.values()) if strategy == 'oversample' else min(counts.values())

    for cls in classes:
        cls_path = data_path / cls
        dest_cls_path = target_dir / cls
        dest_cls_path.mkdir(parents=True, exist_ok=True)

        files = [f for f in cls_path.iterdir() if f.is_file() and f.suffix.lower() in ['.jpg', '.jpeg']]
        n_needed = max_count

        sampled = random.choices(files, k=n_needed) if strategy == 'oversample' else random.sample(files, k=n_needed)

        for f in sampled:
            new_name = f"{f.stem}_{random.randint(10000,99999)}{f.suffix}"
            shutil.copy(f, dest_cls_path/new_name)

    print(f"Balanced dataset saved to: {target_dir}")
    return target_dir

path = Path('/content/drive/MyDrive/eh_classification')

balance_dataset(path, strategy = 'oversample')

import shutil

shutil.move('/content/balanced_data', '/content/drive/MyDrive')

